// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using basurapp.api.Data;

namespace basurapp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("basurapp.api.Models.BasurappUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("lastName");

                    b.Property<byte[]>("passwordHash");

                    b.Property<byte[]>("passwordSalt");

                    b.Property<string>("phone");

                    b.Property<string>("realName");

                    b.Property<int>("role");

                    b.Property<string>("userName");

                    b.HasKey("id");

                    b.ToTable("BasurappUser");
                });

            modelBuilder.Entity("basurapp.api.Models.Delivery", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("altitude");

                    b.Property<int?>("basurappUserContributorid");

                    b.Property<int?>("basurappUserRecolectorid");

                    b.Property<DateTime>("date");

                    b.Property<int>("deliveryState");

                    b.Property<string>("description");

                    b.Property<decimal>("latitude");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.HasIndex("basurappUserContributorid");

                    b.HasIndex("basurappUserRecolectorid");

                    b.ToTable("Delivery");
                });

            modelBuilder.Entity("basurapp.api.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("creatorid");

                    b.Property<string>("description");

                    b.Property<decimal>("price");

                    b.Property<string>("productName");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.HasIndex("creatorid");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("basurapp.api.Models.Delivery", b =>
                {
                    b.HasOne("basurapp.api.Models.BasurappUser", "basurappUserContributor")
                        .WithMany()
                        .HasForeignKey("basurappUserContributorid");

                    b.HasOne("basurapp.api.Models.BasurappUser", "basurappUserRecolector")
                        .WithMany()
                        .HasForeignKey("basurappUserRecolectorid");
                });

            modelBuilder.Entity("basurapp.api.Models.Product", b =>
                {
                    b.HasOne("basurapp.api.Models.BasurappUser", "creator")
                        .WithMany()
                        .HasForeignKey("creatorid");
                });
#pragma warning restore 612, 618
        }
    }
}
